// <auto-generated />
using System;
using BananaGestion.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BananaGestion.Infrastructure.Migrations
{
    [DbContext(typeof(BananaDbContext))]
    [Migration("20260503141704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BananaGestion.Domain.Entities.BoxType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CapacidadKilos")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("box_types", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ComprobanteUrl")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenciaTipo")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("financial_transactions", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestBoxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("HarvestRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<decimal?>("PesoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BoxTypeId");

                    b.HasIndex("HarvestRecordId");

                    b.ToTable("harvest_box_records", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("ColorCinta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ColorNombre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color_nombre");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Semana")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Semana", "Ano")
                        .IsUnique();

                    b.ToTable("harvest_calendars", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestCosecha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnoCosecha")
                        .HasColumnType("integer");

                    b.Property<int>("AnoEncinte")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadRacimos")
                        .HasColumnType("integer");

                    b.Property<string>("ColorCinta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HarvestCalendarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("SemanaCosecha")
                        .HasColumnType("integer");

                    b.Property<int>("SemanaEncinte")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HarvestCalendarId");

                    b.HasIndex("LoteId");

                    b.HasIndex("UserId");

                    b.ToTable("harvest_cosechas", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cliente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmbarque")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HarvestCalendarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Procesada")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HarvestCalendarId");

                    b.HasIndex("NumeroOrden")
                        .IsUnique();

                    b.ToTable("harvest_orders", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnoEncinte")
                        .HasColumnType("integer")
                        .HasColumnName("ano_encinte");

                    b.Property<int>("CantidadRacimosEmbolsados")
                        .HasColumnType("integer");

                    b.Property<string>("ColorCinta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HarvestCalendarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int?>("RacimosPerdidos")
                        .HasColumnType("integer");

                    b.Property<int>("SemanaEncinte")
                        .HasColumnType("integer")
                        .HasColumnName("semana_encinte");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HarvestCalendarId");

                    b.HasIndex("LoteId");

                    b.HasIndex("UserId");

                    b.ToTable("harvest_records", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<decimal>("StockAnterior")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("StockNuevo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Hectareas")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLeida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.OrderBoxDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadEmpacada")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadPlanificada")
                        .HasColumnType("integer");

                    b.Property<Guid>("HarvestOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoxTypeId");

                    b.HasIndex("HarvestOrderId");

                    b.ToTable("order_box_details", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.TaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskConfigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("TaskConfigId");

                    b.HasIndex("UserId");

                    b.ToTable("task_assignments", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.TaskConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FrecuenciaDias")
                        .HasColumnType("integer");

                    b.Property<decimal?>("InsumoCantidad")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("InsumoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiereFirma")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereFoto")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereGps")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoLabor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ProductId");

                    b.ToTable("task_configs", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.TaskLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CantidadInsumoUtilizado")
                        .HasPrecision(10, 2)
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmaUrl")
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<Guid>("TaskAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskConfigId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskAssignmentId")
                        .IsUnique();

                    b.HasIndex("TaskConfigId");

                    b.ToTable("task_logs", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestBoxRecord", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.BoxType", "BoxType")
                        .WithMany("HarvestBoxRecords")
                        .HasForeignKey("BoxTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BananaGestion.Domain.Entities.HarvestRecord", "HarvestRecord")
                        .WithMany("BoxRecords")
                        .HasForeignKey("HarvestRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoxType");

                    b.Navigation("HarvestRecord");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestCosecha", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.HarvestCalendar", "HarvestCalendar")
                        .WithMany()
                        .HasForeignKey("HarvestCalendarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BananaGestion.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BananaGestion.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HarvestCalendar");

                    b.Navigation("Lote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestOrder", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.HarvestCalendar", "HarvestCalendar")
                        .WithMany()
                        .HasForeignKey("HarvestCalendarId");

                    b.Navigation("HarvestCalendar");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestRecord", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.HarvestCalendar", "HarvestCalendar")
                        .WithMany("HarvestRecords")
                        .HasForeignKey("HarvestCalendarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BananaGestion.Domain.Entities.Lote", "Lote")
                        .WithMany("HarvestRecords")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BananaGestion.Domain.Entities.User", "User")
                        .WithMany("HarvestRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HarvestCalendar");

                    b.Navigation("Lote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.Lote", "Lote")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BananaGestion.Domain.Entities.Product", "Product")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BananaGestion.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lote");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.OrderBoxDetail", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.BoxType", "BoxType")
                        .WithMany()
                        .HasForeignKey("BoxTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BananaGestion.Domain.Entities.HarvestOrder", "HarvestOrder")
                        .WithMany("BoxDetails")
                        .HasForeignKey("HarvestOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoxType");

                    b.Navigation("HarvestOrder");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.TaskAssignment", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.Lote", "Lote")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BananaGestion.Domain.Entities.TaskConfig", "TaskConfig")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TaskConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BananaGestion.Domain.Entities.User", "User")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("TaskConfig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.TaskConfig", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.Product", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BananaGestion.Domain.Entities.Product", null)
                        .WithMany("TaskConfigs")
                        .HasForeignKey("ProductId");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.TaskLog", b =>
                {
                    b.HasOne("BananaGestion.Domain.Entities.TaskAssignment", "TaskAssignment")
                        .WithOne("TaskLog")
                        .HasForeignKey("BananaGestion.Domain.Entities.TaskLog", "TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BananaGestion.Domain.Entities.TaskConfig", null)
                        .WithMany("TaskLogs")
                        .HasForeignKey("TaskConfigId");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.BoxType", b =>
                {
                    b.Navigation("HarvestBoxRecords");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestCalendar", b =>
                {
                    b.Navigation("HarvestRecords");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestOrder", b =>
                {
                    b.Navigation("BoxDetails");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.HarvestRecord", b =>
                {
                    b.Navigation("BoxRecords");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.Lote", b =>
                {
                    b.Navigation("HarvestRecords");

                    b.Navigation("InventoryMovements");

                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.Product", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("TaskConfigs");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.TaskAssignment", b =>
                {
                    b.Navigation("TaskLog");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.TaskConfig", b =>
                {
                    b.Navigation("TaskAssignments");

                    b.Navigation("TaskLogs");
                });

            modelBuilder.Entity("BananaGestion.Domain.Entities.User", b =>
                {
                    b.Navigation("HarvestRecords");

                    b.Navigation("TaskAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
